### ISSUE TITLE
It doesn't track masterani

### ISSUE THREAD

**Issue by ghost** [ExillustX/taiga#1]
Read title

**Comment by exil0867** [comment]
Open _settings > Recognition_ and make sure to select `Enable streaming media detection` and `Masterani`.

**Comment by ghost** [comment]
Thank you

**Comment by exil0867** [comment]
No problem!

**Comment by ghost** [comment]
One more thing sorry, will you ever add mac support?

**Comment by exil0867** [comment]
This repository is just a fork from https://github.com/erengy/taiga. That being said, you need to ask the original developer, but it appears that they are planning for a [cross-platform support](https://github.com/erengy/taiga/issues/92).

**Comment by ghost** [comment]
Is there a way I can contact you on Discord for some further inquiries since I don't use github much
